<?php
/**
 * Created by PhpStorm.
 * User: BITM PHP
 * Date: 3/28/2022
 * Time: 4:49 PM
 */

namespace App\Vehicle;

use App\Vehicle\Car;
class SportsCar extends Car
{
public function hello()
{
    return "<br>".'hello'; // TODO: Change the autogenerated stub
}
}